### ISSUE TITLE
Join/Create Button Hidden After Invalid Credentials

### ISSUE THREAD

**Issue by Merfoo** [sunnydan/HivemindGME#1]
Steps to Reproduce
1) Go to https://sunnydan.github.io/HivemindGME/
2) Click "JOIN/CREATE ROOM" button with both Room Name and Username fields empty

Perhaps show the button again after there is text in both input fields?

Pretty sure it was this commit that introduced the current behavior https://github.com/sunnydan/HivemindGME/commit/045fd0b5ceffd7d3f194137af86c1e0f1e4f2954

**Comment by sunnydan** [comment]
Ah, didn't think about invalid credentials. Thanks for pointing this out.

**Comment by sunnydan** [comment]
https://github.com/sunnydan/HivemindGME/commit/8dd7e6e02b745ca81ff9a80855df853fdfafaa81
That should fix it.
